// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfirmationChallenge = { nonce: string, operation_id: string, displayed_digest: string, expires_at_unix_ms: string, };
