// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventEnvelope<T> = { contract_version: number, subscription_id: string, aggregate_type: string, aggregate_id: string, sequence: number, occurred_at_utc: string, operation_id: string | null, body: T, };
