// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestKind } from "./RequestKind";

export type RequestEnvelope<T> = { contract_version: number, request_id: string, window_id: string, profile_id: string | null, expected_revision: number | null, idempotency_key: string | null, kind: RequestKind, body: T, };
