// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamGapPolicy } from "./StreamGapPolicy";

export type StreamDescriptor = { stream_id: string, content_type: string, initial_sequence: number, chunk_limit: number, credit_window: number, gap_policy: StreamGapPolicy, };
