// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamCloseReason = "completed" | "cancelled" | "owner_closed" | "source_closed" | "overflow_gap" | "error";
