[workspace]
resolver = "2"
members = ["apps/desktop/src-tauri"]
default-members = ["apps/desktop/src-tauri"]

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.97"

[workspace.lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "allow"
nursery = "allow"
